            - name: Quality Clouds Build Check for Salesforce
  # You may pin to the exact commit or the version.
  # uses: qualityclouds/action-full-scan@4bc13bbfa27d8eaa0bc4978ac161d148a6f70ac4
  uses: qualityclouds/action-full-scan@1.0.1
  with:
    # You need to provide a valid API key to connect the Quality Clouds ruleset against which your code will be checked
    token: 
    # Use cloud mode to runh a Feature branch scan
    mode: # optional
    # The instance Id. Required when cloud mode is enabled.
    url_id: # optional
    # Use cloud mode to runh a Feature branch scan
    api_url: # optional
    # Customize runner version
    version: # optional
          
